export type PlanTier = "base" | "premium" | "ai_disabled" | string;

export type UsageEvent = {
  id: string;
  owner_id: string;
  user_email?: string | null;
  request_id: string | null;
  event_type: string;
  source: string | null;
  model_provider: string | null;
  model_name: string | null;
  tokens_input: number;
  tokens_output: number;
  tokens_total: number;
  tokens_weighted: number;
  ai_credits_used: number;
  import_credits_used: number;
  cost_usd: number | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
};

export type ProfileRow = {
  id: string;
  name: string | null;
  plan: PlanTier | null;
  subscription_period: "monthly" | "yearly" | null;
  created_at: string | null;
  trial_ends_at: string | null;
  trial_canceled_at?: string | null;
  subscription_status?: string | null;
  language?: string | null;
  country?: string | null;
  bonus_imports: number | null;
  bonus_tokens: number | null;
  trial_imports: number | null;
  trial_tokens: number | null;
  trial_imports_used: number | null;
  trial_tokens_used: number | null;
  trial_translations?: number | null;
  trial_translations_used?: number | null;
  trial_optimizations?: number | null;
  trial_optimizations_used?: number | null;
  trial_ai_messages?: number | null;
  trial_ai_messages_used?: number | null;
  addon_imports?: number | null;
  addon_translations?: number | null;
  addon_optimizations?: number | null;
  addon_ai_messages?: number | null;
};

export type UsageSummary = {
  totalUsers: number;
  baseUsers: number;
  premiumUsers: number;
  trialUsers: number;
  canceledUsers: number;
  canceledTrialUsers: number;
  baseMonthlyUsers: number;
  baseYearlyUsers: number;
  premiumMonthlyUsers: number;
  premiumYearlyUsers: number;
  freeUsers: number;
  usersByCountry: Array<{ label: string; value: number }>;
  usersByLanguage: Array<{ label: string; value: number }>;
  actionTotals: Array<{
    action: string;
    events: number;
    creditsUsed: number;
    costUsd: number;
  }>;
  contextTotals: Array<{
    context: string;
    events: number;
    creditsUsed: number;
    costUsd: number;
  }>;
  creditInventory: Array<{
    action: string;
    planAvailable: number;
    trialAvailable: number;
    addonRemaining: number;
    addonsPurchased: number | null;
    addonsUsed: number | null;
  }>;
  totalImports: number;
  totalAiCredits: number;
  totalCostUsd: number;
  totalWhisperSeconds: number;
  totalVisionImages: number;
  currentPeriodImportsUsed: number;
  currentPeriodTranslationsUsed: number;
  currentPeriodOptimizationsUsed: number;
  currentPeriodAiMessagesUsed: number;
  currentPeriodAiUsed: number;
  totalImportCreditsAvailable: number;
  totalTranslationCreditsAvailable: number;
  totalOptimizationCreditsAvailable: number;
  totalAiMessageCreditsAvailable: number;
  totalAiCreditsAvailable: number;
  activeUsers: number;
  dailySeries: Array<{ date: string; imports: number; aiCredits: number }>;
  bySource: Array<{ label: string; value: number }>;
  byModel: Array<{ label: string; value: number }>;
  modelBreakdown: Array<{ label: string; aiCredits: number; costUsd: number; events: number }>;
  actionModelBreakdown: Array<{
    action: string;
    model: string;
    credits: number;
    costUsd: number;
    events: number;
  }>;
  importBreakdown: Array<{
    requestId: string;
    ownerId: string | null;
    source: string | null;
    action: string;
    model: string;
    createdAt: string;
    credits: number;
    costUsd: number;
    events: number;
  }>;
  sourceImportSeries: Array<{ label: string; points: Array<{ date: string; value: number }> }>;
  actionCountSeries: Array<{ label: string; points: Array<{ date: string; value: number }> }>;
  actionCreditSeries: Array<{ label: string; points: Array<{ date: string; value: number }> }>;
  actionCostSeries: Array<{ label: string; points: Array<{ date: string; value: number }> }>;
  contextCountSeries: Array<{ label: string; points: Array<{ date: string; value: number }> }>;
  costByUser: Array<{
    ownerId: string;
    email: string | null;
    importCredits: number;
    gptMiniCredits: number;
    gpt4oCredits: number;
    visionImages: number;
    whisperSeconds: number;
    totalCostUsd: number;
  }>;
  actionSeries: Array<{ label: string; points: Array<{ date: string; value: number }> }>;
  sourceSeries: Array<{ label: string; points: Array<{ date: string; value: number }> }>;
  contextSeries: Array<{ label: string; points: Array<{ date: string; value: number }> }>;
};
