export const RECIPE_TAGS = [
  "dinner",
  "quick",
  "easy",
  "healthy",
  "vegetarian",
  "dessert",
  "lunch",
  "breakfast",
  "one-pot",
  "comfort food",
  "vegan",
  "gluten-free",
  "snack",
  "baking",
  "spicy",
  "kids-friendly",
  "meal prep",
  "side dish",
  "oven",
  "party",
  "appetizer",
  "soup",
  "salad",
  "make-ahead",
  "high-protein",
  "grill",
  "bbq",
  "family",
  "american",
  "asian",
  "mediterranean",
  "european",
  "latin american",
  "middle eastern",
  "north african",
  "scandinavian",
  "dairy-free",
  "low-carb",
  "keto",
  "seafood",
  "poultry",
  "meat",
  "stew",
  "budget-friendly",
  "under 30 minutes",
];

export const POPULAR_RECIPE_TAG_COUNT = 12;
